# backend/docker-compose.dev.yml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: paldev
      POSTGRES_USER: paldev
      POSTGRES_PASSWORD: paldev
    ports:
      - "5444:5432"
    volumes:
      - pgdev:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d # ← вот эта строка

#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdev:
  minio_data:
